services:
 redis:
  container_name: "redis"
  image: redis
  command: redis-server /usr/local/etc/redis/redis.conf --requirepass mysecretpassword
  ports:
      - "6379:6379"
  environment:
         RDIS_HOST: cache
         REDOS_PORT: 6379
         REDIS_PASSWORD: mysecretpassword

  volumes:
      - "$PWD/redis.conf:/usr/local/etc/redis/redis.conf"




